# Generated by Django 5.2.3 on 2025-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellDepth', models.JSONField(default=list)),
                ('bitDepth', models.JSONField(default=list)),
                ('wOB', models.JSONField(default=list)),
                ('hookLoad', models.JSONField(default=list)),
                ('sPP', models.JSONField(default=list)),
                ('flowRateIn', models.JSONField(default=list)),
                ('surfaceTorque', models.JSONField(default=list)),
                ('surfaceRPM', models.JSONField(default=list)),
                ('blockPosition', models.JSONField(default=list)),
                ('trippingSpeed', models.JSONField(default=list)),
                ('rOP', models.JSONField(default=list)),
            ],
        ),
    ]
