# Generated by Django 5.2.3 on 2025-06-24 19:31

import predictionserver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='bitDepth',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='blockPosition',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='flowRateIn',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='hookLoad',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='rOP',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sPP',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='surfaceRPM',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='surfaceTorque',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='trippingSpeed',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='wOB',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='wellDepth',
            field=models.JSONField(default=list),
        ),
    ]
