# Generated by Django 5.2.3 on 2025-07-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionserver', '0003_alter_sensordata_bitdepth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='hookLoad',
        ),
    ]
